<a href="https://colab.research.google.com/github/itsmaul/bangkit-capstone/blob/main/Clean_TrainingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
adit_df = pd.read_csv("dataset_adit.csv")
adit_df.sample(20)

,ID,NOREK,TGL_TRAN,TGL_EFEKTIF,JAM_TRAN,SEQ,DESK_TRAN,SALDO_AWAL_MUTASI,MUTASI_DEBET,MUTASI_KREDIT,SALDO_AKHIR_MUTASI,GLSIGN,TRUSER,KODE_TRAN,KODE_TRAN_TELLER,TRREMK,TLBDS1,TLBDS2,REMARK_CUSTOM
25,7,479101005292506,2024-08-21 06:23:21,2024-08-21 06:23:21,62321.0,2121.0,601301085548007600051368,371547.8,300000.0,0.0,71547.8,Db,9966111.0,2.0,2501.0,601301085548007600051368,NaN,NaN,601301085548007600051368
45,18,479101005292506,2024-10-30 08:12:31,2024-10-30 08:12:31,81231.0,41480.0,BFST7391631283 NBMB:CENAIDJA 20241030BRINIDJA0...,470795.8,100000.0,0.0,370795.8,Db,8888043.0,2.0,9973.0,BFST7391631283 NBMB:CENAIDJA,ESB:NBMB:0008G00F:754185519035,20241030BRINIDJA010O0244829556,BFST7391631283 NBMB:CENAIDJA
40,13,479101005292506,2024-10-30 08:02:25,2024-10-30 08:02:25,80225.0,101424.0,6013010855480076#754182244496#NBMB#TRFLA LA167...,1413547.8,6500.0,0.0,1407047.8,Db,8888286.0,2.0,8508.0,6013010855480076#754182244496#NBMB#TRFLA,ESB:NBMB:0005N00F:754182244496,LA167891050001200093NBMB6013010855480076,6013010855480076#754182244496#NBMB#TRFLA
46,19,479101005292506,2024-10-30 08:12:31,2024-10-30 08:12:31,81231.0,41480.0,BFST7391631283 NBMB:CENAIDJA 20241030BRINIDJA0...,370795.8,2500.0,0.0,368295.8,Db,8888043.0,2.0,9973.0,BFST7391631283 NBMB:CENAIDJA,ESB:NBMB:0008G00F:754185519035,20241030BRINIDJA010O0244829556,BFST7391631283 NBMB:CENAIDJA
56,7,479101005292506,2024-11-04 17:49:19,2024-11-04 17:49:19,174919.0,107138.0,BFST8850926345 NBMB:CENAIDJA 20241104BRINIDJA0...,3393795.8,100000.0,0.0,3293795.8,Db,8888227.0,2.0,9973.0,BFST8850926345 NBMB:CENAIDJA,ESB:NBMB:0008G00F:756830640744,20241104BRINIDJA010O0204706545,BFST8850926345 NBMB:CENAIDJA
61,12,479101005292506,2024-11-07 20:09:36,2024-11-07 20:09:36,200936.0,110290.0,BFST479101005292506AHYARBACHTIA:BSMDIDJA 20241...,3788795.8,0.0,2500000.0,6288795.8,Cr,8888637.0,1.0,8154.0,BFST479101005292506AHYARBACHTIA:BSMDIDJA,ESB:BFST:0008N:20241107FASTIDJA01017106767,20241107BSMDIDJA010O0271270418,BFST479101005292506AHYARBACHTIA:BSMDIDJA
9,4,479101005292506,2024-02-28 20:09:07,2024-02-28 20:09:07,200907.0,71437.0,BFST002501002620303 NBMB:AGTBIDJA 20240228BRIN...,3426547.8,3000000.0,0.0,426547.8,Db,8888504.0,2.0,9973.0,BFST002501002620303 NBMB:AGTBIDJA,ESB:NBMB:0008G00F:653734400121,20240228BRINIDJA010O0229611484,BFST002501002620303 NBMB:AGTBIDJA
6,1,479101005292506,2024-02-26 18:09:20,2024-02-26 18:09:20,180920.0,7007018.0,2024022692285007312 WS_OB;2024022692285007312;...,51547.8,0.0,4575000.0,4626547.8,Cr,371854.0,5.0,8700.0,2024022692285007312,ESB:T:0371854:S:0371892:WSOB,WS_OB;2024022692285007312;44409,2024022692285007312
15,1,479101005292506,2024-04-01 00:00:00,2024-04-01 00:00:00,NaN,NaN,Transaksi tidak ditemukan,71547.8,0.0,0.0,71547.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,11,479101005292506,2024-10-30 08:00:24,2024-10-30 08:00:24,80024.0,61415.0,BFST002501002620303 NBMB:AGTBIDJA 20241030BRIN...,4619047.8,2500.0,0.0,4616547.8,Db,8888371.0,2.0,9973.0,BFST002501002620303 NBMB:AGTBIDJA,ESB:NBMB:0008G00F:754181614360,20241030BRINIDJA010O0244718555,BFST002501002620303 NBMB:AGTBIDJA
55,6,479101005292506,2024-11-04 11:52:07,2024-11-04 11:52:07,115207.0,3648.0,BFST7391631283 NBMB:CENAIDJA 20241104BRINIDJA0...,3396295.8,2500.0,0.0,3393795.8,Db,8888151.0,2.0,9973.0,BFST7391631283 NBMB:CENAIDJA,ESB:NBMB:0008G00F:756668815959,20241104BRINIDJA010O0200475798,BFST7391631283 NBMB:CENAIDJA
18,1,479101005292506,2024-07-01 00:00:00,2024-07-01 00:00:00,NaN,NaN,Transaksi tidak ditemukan,71547.8,0.0,0.0,71547.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,4,479101005292506,2024-11-03 15:50:02,2024-11-03 15:50:02,155002.0,5037307.0,5899290032859480#000000006302#ATM #TRFLA TRF B...,3033295.8,0.0,800000.0,3833295.8,Cr,888904.0,1.0,8514.0,5899290032859480#000000006302#ATM #TRFLA,LA 479101005292506ATM 5899290032859480,TRF BERSAMA FROM AMAT BIN ITA,Transfer Antar Bank Dari Amat Bin Ita
26,8,479101005292506,2024-08-27 20:35:59,2024-08-27 20:35:59,203559.0,3410362.0,5899290032859480#000000004877#ATM #TRFLA TRF B...,71547.8,0.0,150000.0,221547.8,Cr,888767.0,1.0,8514.0,5899290032859480#000000004877#ATM #TRFLA,LA 479101005292506ATM 5899290032859480,TRF BERSAMA FROM AMAT BIN ITA,Transfer Antar Bank Dari Amat Bin Ita
4,5,479101005292506,2024-01-31 09:48:19,2024-01-31 09:48:19,94819.0,83068.0,BFST7127090224 NBMB:BSMDIDJA 20240131BRINIDJA0...,294047.8,240000.0,0.0,54047.8,Db,8888599.0,2.0,9973.0,BFST7127090224 NBMB:BSMDIDJA,ESB:NBMB:0008G00F:642414285324,20240131BRINIDJA010O0237047376,BFST7127090224 NBMB:BSMDIDJA
71,22,479101005292506,2024-11-11 10:48:21,2024-11-11 10:48:21,104821.0,143116.0,BFST2757514521 NBMB:CENAIDJA 20241111BRINIDJA0...,3236995.8,150000.0,0.0,3086995.8,Db,8888254.0,2.0,9973.0,BFST2757514521 NBMB:CENAIDJA,ESB:NBMB:0008G00F:759740957843,20241111BRINIDJA010O0226253468,BFST2757514521 NBMB:CENAIDJA
17,1,479101005292506,2024-06-01 00:00:00,2024-06-01 00:00:00,NaN,NaN,Transaksi tidak ditemukan,71547.8,0.0,0.0,71547.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,8,479101005292506,2024-10-29 13:19:05,2024-10-29 13:19:05,131905.0,105568.0,BFST479101005292506ADITYA DAFFA:BTANIDJA 20241...,4819047.8,0.0,800000.0,5619047.8,Cr,8888692.0,1.0,8154.0,BFST479101005292506ADITYA DAFFA:BTANIDJA,ESB:BFST:0008N:20241029FASTIDJA010267860,20241029BTANIDJA010O0241997162,BFST479101005292506ADITYA DAFFA:BTANIDJA
37,10,479101005292506,2024-10-30 08:00:24,2024-10-30 08:00:24,80024.0,61415.0,BFST002501002620303 NBMB:AGTBIDJA 20241030BRIN...,7619047.8,3000000.0,0.0,4619047.8,Db,8888371.0,2.0,9973.0,BFST002501002620303 NBMB:AGTBIDJA,ESB:NBMB:0008G00F:754181614360,20241030BRINIDJA010O0244718555,BFST002501002620303 NBMB:AGTBIDJA
0,1,479101005292506,2024-01-29 23:16:47,2024-01-29 23:16:47,231647.0,33048.0,NBMB NIKEN WIDYA TO SURATUN ESB:NBMB:0001500F:...,61547.8,0.0,2735000.0,2796547.8,Cr,8888168.0,1.0,8506.0,NBMB NIKEN WIDYA TO SURATUN,ESB:NBMB:0001500F:641894918038,NaN,Transfer Dari Niken Widya via BRImo

In [3]:
alus_df = pd.read_csv("dataset_alus.csv")
alus_df.sample(20)

,ID,NOREK,TGL_TRAN,TGL_EFEKTIF,JAM_TRAN,SEQ,DESK_TRAN,SALDO_AWAL_MUTASI,MUTASI_DEBET,MUTASI_KREDIT,SALDO_AKHIR_MUTASI,GLSIGN,TRUSER,KODE_TRAN,KODE_TRAN_TELLER,TRREMK,TLBDS1,TLBDS2,REMARK_CUSTOM
70,8,12301083861508,2024-04-02 09:39:55,2024-04-02 00:00:00,93955,104449,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,400750.0,1500.0,0.0,399250.0,Db,8888462,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:667675923240,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
220,10,12301083861508,2024-10-14 11:09:47,2024-10-14 00:00:00,110947,8043777,BRIVA88810081285686759NBMBDNID ARFXXX HA BRIVA...,857950.0,90000.0,0.0,767950.0,Db,8888602,4,6669.0,BRIVA88810081285686759NBMBDNID ARFXXX HA,ESB:NBMB:0200200P:747429326892,BRIVA 88810081285686759NBMBDNID ARFXXX H,Top Up DANA ARFXXX HA 0812xxxx759 via BRImo
200,16,12301083861508,2024-09-16 10:21:55,2024-09-16 00:00:00,102155,62152,PLN-PRA 56019014093NBMB5221840817338040 ESB:NB...,678200.0,50000.0,0.0,628200.0,Db,8888426,2,8508.0,PLN-PRA 56019014093NBMB5221840817338040,ESB:NBMB:0400200T:735348999673,NaN,Beli Token PLN 56019014093 via BRImo
227,17,12301083861508,2024-10-20 06:23:25,2024-10-20 00:00:00,62325,5057004,PLN-PRA 56019014093NBMB5221840817338040 ESB:NB...,579450.0,3000.0,0.0,576450.0,Db,8888338,2,8508.0,PLN-PRA 56019014093NBMB5221840817338040,ESB:NBMB:20006PLN:749902127190,NaN,Beli Token PLN 56019014093 via BRImo
48,8,12301083861508,2024-03-04 07:42:34,2024-03-04 00:00:00,74234,61901,BRIVA88810088299538305NBMBDNID RISXX AUL BRIVA...,650500.0,200000.0,0.0,450500.0,Db,8888555,4,6669.0,BRIVA88810088299538305NBMBDNID RISXX AUL,ESB:NBMB:0200200P:655660605435,BRIVA 88810088299538305NBMBDNID RISXX AU,Top Up DANA RISXX AUL 0882xxxx305 via BRImo
166,9,12301083861508,2024-08-12 19:11:28,2024-08-12 00:00:00,191128,0,081286178536|1SMS|09/08/2024-09/08/2024,2930500.0,750.0,0.0,2929750.0,Db,BRIMDBT,582,NaN,081286178536|1SMS|09/08/2024-09/08/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 1 Notifikasi
169,12,12301083861508,2024-08-14 19:48:19,2024-08-14 00:00:00,194819,111563,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,2828250.0,20000.0,0.0,2808250.0,Db,8888250,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:721957353921,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
192,8,12301083861508,2024-09-12 15:15:38,2024-09-12 00:00:00,151538,84704,BFST1730016357049 NBMB:BMRIIDJA 20240912BRINID...,1024500.0,2500.0,0.0,1022000.0,Db,8888109,2,9973.0,BFST1730016357049 NBMB:BMRIIDJA,ESB:NBMB:0008G00F:733854171012,20240912BRINIDJA010O0224040705,BFST1730016357049 NBMB:BMRIIDJA
211,1,12301083861508,2024-10-01 15:34:51,2024-10-01 00:00:00,153451,9068844,BRIVA88810081286178536NBMBDNID ALUXXXXX BRIVA ...,657450.0,100000.0,0.0,557450.0,Db,8888395,4,6669.0,BRIVA88810081286178536NBMBDNID ALUXXXXX,ESB:NBMB:0200200P:741770742795,BRIVA 88810081286178536NBMBDNID ALUXXXXX,Top Up DANA ALUXXXXX 0812xxxx536 via BRImo
41,1,12301083861508,2024-03-01 14:46:36,2024-03-01 00:00:00,144636,9645652,WBNK DEYA DAMAYANTI TO TO ALUSTINA SUCI FROM43...,251000.0,0.0,1200000.0,1451000.0,Cr,0888907,1,8506.0,WBNK DEYA DAMAYANTI TO TO ALUSTINA SUCI,FROM432901018417534 TO012301083861508WBN,NaN,Transfer Dari Deya Damayanti via BRILink
6,7,12301083861508,2024-01-04 23:59:00,1/4/2024 0:00,235959,0,081286178536|1SMS|02/01/2024-02/01/2024,886500.0,500.0,0.0,886000.0,Db,DDY402,582,NaN,081286178536|1SMS|02/01/2024-02/01/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 1 Notifikasi
141,15,12301083861508,2024-07-22 10:17:18,2024-07-22 00:00:00,101718,9002882,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,7521000.0,1500.0,0.0,7519500.0,Db,8888206,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:712236349452,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
208,24,12301083861508,2024-09-24 14:57:41,2024-09-24 00:00:00,145741,1182662,6013011130242596000000000349,965700.0,300000.0,0.0,665700.0,Db,0888300,2,9992.0,6013011130242596000000000349,NaN,NaN,6013011130242596000000000349
24,5,12301083861508,2024-02-02 19:47:49,2024-02-02 00:00:00,194749,52685,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,567500.0,1500.0,0.0,566000.0,Db,8888374,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:643673722995,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
242,6,12301083861508,2024-11-07 18:02:00,11/7/2024 0:00,180229,166953,BRIVA88810081286178536NBMBDNID ALUXXXXX BRIVA ...,560700.0,50000.0,0.0,510700.0,Db,8888215,4,6669.0,BRIVA88810081286178536NBMBDNID ALUXXXXX,ESB:NBMB:0200200P:758211987117,BRIVA 88810081286178536NBMBDNID ALUXXXXX,Top Up DANA ALUXXXXX 0812xxxx536 via BRImo
153,27,12301083861508,2024-07-30 13:31:08,2024-07-30 00:00:00,133108,189892,6013011130242596000000000135,5788000.0,3000000.0,0.0,2788000.0,Db,0888289,2,9992.0,6013011130242596000000000135,NaN,NaN,6013011130242596000000000135
196,12,12301083861508,2024-09-13 10:08:16,2024-09-13 00:00:00,100816,142258,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,981200.0,1500.0,0.0,979700.0,Db,8888222,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:734154007017,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
4,5,12301083861508,2024-01-02 11:12:00,1/2/2024 0:00,111258,24351,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,903000.0,15000.0,0.0,888000.0,Db,8888163,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:630454648676,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo
150,24,12301083861508,2024-07-30 08:36:22,2024-07-30 00:00:00,83622,61860,BFST012301083861508ALFIA MEILAN:PDJBIDJA ESB:B...,7795500.0,0.0,1000000.0,8795500.0,Cr,8888630,1,8154.0,BFST012301083861508ALFIA MEILAN:PDJBIDJA,ESB:BFST:0008N:20240730FASTIDJA010625917,NaN,BFST012301083861508ALFIA MEILAN:PDJBIDJA
25,6,12301083861508,2024-02-02 19:48:17,2024-02-02 00:00:00,194817,32650,PUL-SIM 081286178536NBMB5221840817338040 ESB:N...,566000.0,100000.0,0.0,466000.0,Db,8888218,2,8508.0,PUL-SIM 081286178536NBMB5221840817338040,ESB:NBMB:0100101C:643673947597,NaN,Beli Pulsa Simpati 0812xxxx536 via BRImo

In [4]:
amin_df = pd.read_csv("dataset_amin.csv")
amin_df.sample(20)

,ID,NOREK,TGL_TRAN,TGL_EFEKTIF,JAM_TRAN,SEQ,DESK_TRAN,SALDO_AWAL_MUTASI,MUTASI_DEBET,MUTASI_KREDIT,SALDO_AKHIR_MUTASI,GLSIGN,TRUSER,KODE_TRAN,KODE_TRAN_TELLER,TRREMK,TLBDS1,TLBDS2,REMARK_CUSTOM
222,16,678701037253531,2024-07-14 08:26:10,2024-07-14 00:00:00,82610,0,089529961557|2SMS|09/07/2024-09/07/2024,258626.27,1500.0,0.0,257126.27,Db,BRIMDBT,582,NaN,089529961557|2SMS|09/07/2024-09/07/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 2 Notifikasi
25,3,678701037253531,2023-08-08 12:53:08,2023-08-08 00:00:00,125308,9061936,BRIVA128082227497301NBMBjXXXXXXXXXXXXXXX BRIVA...,224970.27,186450.0,0.0,38520.27,Db,8888434,4,6669.0,BRIVA128082227497301NBMBjXXXXXXXXXXXXXXX,ESB:NBMB:0200200P:568959258736,BRIVA 128082227497301NBMBjXXXXXXXXXXXX,BRIVA128082227497301NBMBjXXXXXXXXXXXXXXX
27,5,678701037253531,2023-08-12 09:57:39,2023-08-12 00:00:00,95739,12212,089529961557 00260405 000000012212,1238520.27,400000.0,0.0,838520.27,Db,9854667,2,2501.0,089529961557 00260405 000000012212,089529961557 00260405 000000012212,NaN,089529961557 00260405 000000012212
149,27,678701037253531,2024-04-19 02:58:07,2024-04-19 00:00:00,25807,140671,PUL-SIM 082231667638NBMB6013010205151492 ESB:N...,1567244.27,1500.0,0.0,1565744.27,Db,8888485,2,8508.0,PUL-SIM 082231667638NBMB6013010205151492,ESB:NBMB:0100101C:674317432548,NaN,Beli Pulsa Simpati 0822xxxx638 via BRImo
29,7,678701037253531,2023-08-14 11:22:49,2023-08-14 00:00:00,112249,9061527,THREE 089529961557NBMB6013010205151492 ESB:NBM...,454520.27,150000.0,0.0,304520.27,Db,8888031,2,8541.0,THREE 089529961557NBMB6013010205151492,ESB:NBMB:0100803C:571183267862,NaN,Beli Pulsa Three 0895xxxx557 via BRImo
242,15,678701037253531,2024-08-16 23:59:59,2024-08-16 00:00:00,235959,0,Admin Fee,43014.27,5500.0,0.0,37514.27,Db,NaN,453,NaN,NaN,NaN,NaN,Admin Fee
167,15,678701037253531,2024-05-11 08:44:47,2024-05-11 00:00:00,84447,102417,QRIS683132326818#9360000210043076322 ESB:NBMB:...,1663904.27,16000.0,0.0,1647904.27,Db,8888009,2,8508.0,QRIS683132326818#9360000210043076322,ESB:NBMB:0007I00P:683132326818,QRIS683132326818#9360000210043076322,Bayar QRIS Non BRI Merchant: QRIS683132326818
235,8,678701037253531,2024-08-14 18:50:27,2024-08-14 00:00:00,185027,14676,089529961557 00260405 000000014676,4572514.27,100000.0,0.0,4472514.27,Db,9854667,2,2501.0,089529961557 00260405 000000014676,089529961557 00260405 000000014676,NaN,089529961557 00260405 000000014676
250,5,678701037253531,2024-09-10 09:20:37,2024-09-10 00:00:00,92037,0,089529961557|2SMS|05/09/2024-06/09/2024,298014.27,1500.0,0.0,296514.27,Db,BRIMDBT,582,NaN,089529961557|2SMS|05/09/2024-06/09/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 2 Notifikasi
4,5,678701037253531,2023-09-04 14:02:32,2023-09-04 00:00:00,140232,4266,089529961557 00450971 000000004266,1032020.27,100000.0,0.0,932020.27,Db,9854075,2,2501.0,089529961557 00450971 000000004266,089529961557 00450971 000000004266,NaN,089529961557 00450971 000000004266
253,8,678701037253531,2024-09-19 16:18:07,2024-09-19 00:00:00,161807,48752,NBMB AMIN AFIF RAFI TO FLIPTECH LENTERA ESB:NB...,288514.27,250131.0,0.0,38383.27,Db,8888097,2,8508.0,NBMB AMIN AFIF RAFI TO FLIPTECH LENTERA,ESB:NBMB:0001500F:736707049014,NaN,Transfer Ke Fliptech Lentera via BRImo
41,7,678701037253531,2023-10-16 00:00:00,2023-10-16 00:00:00,0,0,Monthly Fee ATM,168440.27,2500.0,0.0,165940.27,Db,NaN,452,NaN,NaN,NaN,NaN,Monthly Fee ATM
176,24,678701037253531,2024-05-22 07:36:02,2024-05-22 00:00:00,73602,0,089529961557|3SMS|18/05/2024-18/05/2024,2040904.27,2250.0,0.0,2038654.27,Db,BRIMDBT,582,NaN,089529961557|3SMS|18/05/2024-18/05/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 3 Notifikasi
200,20,678701037253531,2024-06-24 18:16:20,2024-06-24 00:00:00,181620,9008060,NBMB NABILA SANDRA TO AMIN AFIF RAFI'I ESB:NBM...,427635.27,0.0,2000000.0,2427635.27,Cr,8888579,1,8506.0,NBMB NABILA SANDRA TO AMIN AFIF RAFI'I,ESB:NBMB:0001500F:700997618124,NaN,Transfer Dari Nabila Sandra via BRImo
237,10,678701037253531,2024-08-15 14:00:47,2024-08-15 00:00:00,140047,66361,BRIVA10182012203040202NBMBAMIN AFIF RAFI BRIVA...,4372514.27,4245000.0,0.0,127514.27,Db,8888078,4,6669.0,BRIVA10182012203040202NBMBAMIN AFIF RAFI,ESB:NBMB:0200200P:722219121816,BRIVA 10182012203040202NBMBAMIN AFIF RAF,BRIVA10182012203040202NBMBAMIN AFIF RAFI
132,10,678701037253531,2024-04-06 23:59:59,2024-04-06 00:00:00,235959,0,089529961557|1SMS|01/04/2024-01/04/2024,778215.27,750.0,0.0,777465.27,Db,DDY402,582,NaN,089529961557|1SMS|01/04/2024-01/04/2024,NaN,NaN,Biaya SMS Notifikasi Sejumlah 1 Notifikasi
144,22,678701037253531,2024-04-16 22:45:37,2024-04-16 00:00:00,224537,52646,BRIVA80777089529961557NBMBTKP2625693472 BRIVA ...,1976890.27,332396.0,0.0,1644494.27,Db,8888344,4,6669.0,BRIVA80777089529961557NBMBTKP2625693472,ESB:NBMB:0200200P:673529112742,BRIVA 80777089529961557NBMBTKP2625693472,Pembayaran Tokopedia 0895xxxx557 via BRImo
73,18,678701037253531,2023-12-30 20:38:53,2023-12-30 00:00:00,203853,30513,089529961557 00861563 000000030513,196129.27,100000.0,0.0,96129.27,Db,9854674,2,2501.0,089529961557 00861563 000000030513,089529961557 00861563 000000030513,NaN,089529961557 00861563 000000030513
158,6,678701037253531,2024-05-05 10:02:10,2024-05-05 00:00:00,100210,83498,THREE 089529961557NBMB6013010205151492 ESB:NBM...,1827654.27,150000.0,0.0,1677654.27,Db,8888066,2,8541.0,THREE 089529961557NBMB6013010205151492,ESB:NBMB:0100803C:680745211863,NaN,Beli Pulsa Three 0895xxxx557 via BRImo
9,10,678701037253531,2023-09-15 16:03:04,2023-09-15 00:00:00,160304,85978,QRIS584211772052#9360000210043076322 ESB:NBMB:...,1018520.27,513400.0,0.0,505120.27,Db,8888390,2,8508.0,QRIS584211772052#9360000210043076322,ESB:NBMB:0007I00P:584211772052,QRIS584211772052#9360000210043076322,Bayar QRIS Non BRI Merchant: QRIS584211772052

In [5]:
def assessing_data(df):
    print(f"\n---TABLE INFO---\n")
    df.info()

    print(f"\n---MISSING VALUES---\n")
    print(df.isna().sum())

    print(f"\n---DUPLICATE DATA---\n")
    print(df.duplicated().sum())

    print(f"\n---STATISTICS PARAMETER---\n")
    print(df.describe())

In [6]:
assessing_data(adit_df)

---TABLE INFO---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  78 non-null     int64
 1   NOREK               78 non-null     int64
 2   TGL_TRAN            78 non-null     object
 3   TGL_EFEKTIF         78 non-null     object
 4   JAM_TRAN            72 non-null     float64
 5   SEQ                 72 non-null     float64
 6   DESK_TRAN           78 non-null     object
 7   SALDO_AWAL_MUTASI   78 non-null     float64
 8   MUTASI_DEBET        78 non-null     float64
 9   MUTASI_KREDIT       78 non-null     float64
 10  SALDO_AKHIR_MUTASI  78 non-null     float64
 11  GLSIGN              72 non-null     object
 12  TRUSER              72 non-null     float64
 13  KODE_TRAN           72 non-null     float64
 14  KODE_TRAN_TELLER    72 non-null     float64
 15  TRREMK              71 non-null     object
 16  TLBDS1              61 non-null     object
 17  TLBDS2              52 non-null     object
 18  REMARK_CUSTOM       72 non-null     object
dtypes: float64(9), int64(2), object(8)
memory usage: 11.7+ KB

---MISSING VALUES---

ID                     0
NOREK                  0
TGL_TRAN               0
TGL_EFEKTIF            0
JAM_TRAN               6
SEQ                    6
DESK_TRAN              0
SALDO_AWAL_MUTASI      0
MUTASI_DEBET           0
MUTASI_KREDIT          0
SALDO_AKHIR_MUTASI     0
GLSIGN                 6
TRUSER                 6
KODE_TRAN              6
KODE_TRAN_TELLER       6
TRREMK                 7
TLBDS1                17
TLBDS2                26
REMARK_CUSTOM          6
dtype: int64

---DUPLICATE DATA---

0

---STATISTICS PARAMETER---

              ID         NOREK       JAM_TRAN           SEQ  \
count  78.000000  7.800000e+01      72.000000  7.200000e+01
mean    9.717949  4.791010e+14  141827.097222  1.582229e+06
std     7.769232  1.006473e+00   51557.517393  2.817608e+06
min     1.000000  4.791010e+14   62142.000000  1.702000e+03
25%     3.000000  4.791010e+14   94428.500000  4.148000e+04
50%     7.000000  4.791010e+14  123522.500000  1.028330e+05
75%    15.750000  4.791010e+14  191263.250000  1.175518e+06
max    28.000000  4.791010e+14  231647.000000  9.000009e+06

       SALDO_AWAL_MUTASI  MUTASI_DEBET  MUTASI_KREDIT  SALDO_AKHIR_MUTASI  \
count       7.800000e+01  7.800000e+01   7.800000e+01        7.800000e+01
mean        2.125674e+06  2.952443e+05   3.353846e+05        2.165814e+06
std         1.920600e+06  6.813437e+05   8.597394e+05        1.909586e+06
min         5.154780e+04  0.000000e+00   0.000000e+00        5.154780e+04
25%         3.332348e+05  0.000000e+00   0.000000e+00        3.689208e+05
50%         1.410298e+06  2.500000e+03   0.000000e+00        1.640922e+06
75%         3.395671e+06  2.505000e+05   0.000000e+00        3.395671e+06
max         7.619048e+06  3.203000e+06   4.575000e+06        7.619048e+06

             TRUSER  KODE_TRAN  KODE_TRAN_TELLER
count  7.200000e+01  72.000000         72.000000
mean   7.746357e+06   1.930556       8409.083333
std    3.061863e+06   0.810606       2390.666085
min    3.718510e+05   1.000000       2117.000000
25%    8.888068e+06   2.000000       8507.500000
50%    8.888291e+06   2.000000       8700.000000
75%    8.888528e+06   2.000000       9973.000000
max    9.966571e+06   5.000000       9973.000000

In [7]:
assessing_data(alus_df)

---TABLE INFO---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  253 non-null    int64
 1   NOREK               253 non-null    int64
 2   TGL_TRAN            253 non-null    object
 3   TGL_EFEKTIF         253 non-null    object
 4   JAM_TRAN            253 non-null    int64
 5   SEQ                 253 non-null    int64
 6   DESK_TRAN           253 non-null    object
 7   SALDO_AWAL_MUTASI   253 non-null    float64
 8   MUTASI_DEBET        253 non-null    float64
 9   MUTASI_KREDIT       253 non-null    float64
 10  SALDO_AKHIR_MUTASI  253 non-null    float64
 11  GLSIGN              253 non-null    object
 12  TRUSER              233 non-null    object
 13  KODE_TRAN           253 non-null    int64
 14  KODE_TRAN_TELLER    213 non-null    float64
 15  TRREMK              233 non-null    object
 16  TLBDS1              192 non-null    object
 17  TLBDS2              95 non-null     object
 18  REMARK_CUSTOM       253 non-null    object
dtypes: float64(5), int64(5), object(9)
memory usage: 37.7+ KB

---MISSING VALUES---

ID                      0
NOREK                   0
TGL_TRAN                0
TGL_EFEKTIF             0
JAM_TRAN                0
SEQ                     0
DESK_TRAN               0
SALDO_AWAL_MUTASI       0
MUTASI_DEBET            0
MUTASI_KREDIT           0
SALDO_AKHIR_MUTASI      0
GLSIGN                  0
TRUSER                 20
KODE_TRAN               0
KODE_TRAN_TELLER       40
TRREMK                 20
TLBDS1                 61
TLBDS2                158
REMARK_CUSTOM           0
dtype: int64

---DUPLICATE DATA---

0

---STATISTICS PARAMETER---

               ID         NOREK       JAM_TRAN           SEQ  \
count  253.000000  2.530000e+02     253.000000  2.530000e+02
mean    12.652174  1.230108e+13  137295.596838  2.164927e+06
std      7.548097  0.000000e+00   61672.332774  3.497819e+06
min      1.000000  1.230108e+13       0.000000  0.000000e+00
25%      6.000000  1.230108e+13   93929.000000  2.252600e+04
50%     12.000000  1.230108e+13  133108.000000  1.044490e+05
75%     19.000000  1.230108e+13  191109.000000  4.326253e+06
max     31.000000  1.230108e+13  235959.000000  9.894400e+06

       SALDO_AWAL_MUTASI  MUTASI_DEBET  MUTASI_KREDIT  SALDO_AKHIR_MUTASI  \
count       2.530000e+02  2.530000e+02   2.530000e+02        2.530000e+02
mean        1.537512e+06  1.150644e+05   1.109170e+05        1.533365e+06
std         1.811024e+06  3.909758e+05   5.924477e+05        1.811881e+06
min         7.000000e+04  0.000000e+00   0.000000e+00        7.000000e+04
25%         5.115000e+05  1.500000e+03   0.000000e+00        5.115000e+05
50%         8.360000e+05  6.000000e+03   0.000000e+00        8.330000e+05
75%         1.540500e+06  1.000000e+05   0.000000e+00        1.539750e+06
max         8.795500e+06  3.000000e+06   7.000000e+06        8.795500e+06

        KODE_TRAN  KODE_TRAN_TELLER
count  253.000000        213.000000
mean    83.865613       8413.380282
std    189.942780       1216.735034
min      1.000000       2501.000000
25%      2.000000       8154.000000
50%      2.000000       8508.000000
75%      4.000000       8700.000000
max    582.000000       9992.000000

In [8]:
assessing_data(amin_df)

---TABLE INFO---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  281 non-null    int64
 1   NOREK               281 non-null    int64
 2   TGL_TRAN            281 non-null    object
 3   TGL_EFEKTIF         281 non-null    object
 4   JAM_TRAN            281 non-null    int64
 5   SEQ                 281 non-null    int64
 6   DESK_TRAN           281 non-null    object
 7   SALDO_AWAL_MUTASI   281 non-null    float64
 8   MUTASI_DEBET        281 non-null    float64
 9   MUTASI_KREDIT       281 non-null    float64
 10  SALDO_AKHIR_MUTASI  281 non-null    float64
 11  GLSIGN              281 non-null    object
 12  TRUSER              249 non-null    object
 13  KODE_TRAN           281 non-null    int64
 14  KODE_TRAN_TELLER    219 non-null    float64
 15  TRREMK              249 non-null    object
 16  TLBDS1              219 non-null    object
 17  TLBDS2              67 non-null     object
 18  REMARK_CUSTOM       281 non-null    object
dtypes: float64(5), int64(5), object(9)
memory usage: 41.8+ KB

---MISSING VALUES---

ID                      0
NOREK                   0
TGL_TRAN                0
TGL_EFEKTIF             0
JAM_TRAN                0
SEQ                     0
DESK_TRAN               0
SALDO_AWAL_MUTASI       0
MUTASI_DEBET            0
MUTASI_KREDIT           0
SALDO_AKHIR_MUTASI      0
GLSIGN                  0
TRUSER                 32
KODE_TRAN               0
KODE_TRAN_TELLER       62
TRREMK                 32
TLBDS1                 62
TLBDS2                214
REMARK_CUSTOM           0
dtype: int64

---DUPLICATE DATA---

0

---STATISTICS PARAMETER---

               ID         NOREK       JAM_TRAN           SEQ  \
count  281.000000  2.810000e+02     281.000000  2.810000e+02
mean    10.416370  6.787010e+14  136781.964413  1.006565e+06
std      6.841649  2.629683e+00   66852.756462  2.684318e+06
min      1.000000  6.787010e+14       0.000000  0.000000e+00
25%      5.000000  6.787010e+14   91714.000000  1.773000e+03
50%      9.000000  6.787010e+14  140956.000000  4.292300e+04
75%     15.000000  6.787010e+14  190705.000000  1.267400e+05
max     30.000000  6.787010e+14  235959.000000  9.295206e+06

       SALDO_AWAL_MUTASI  MUTASI_DEBET  MUTASI_KREDIT  SALDO_AKHIR_MUTASI  \
count       2.810000e+02  2.810000e+02   2.810000e+02        2.810000e+02
mean        8.389935e+05  1.659982e+05   1.659440e+05        8.389392e+05
std         1.083809e+06  5.817941e+05   8.237038e+05        1.083849e+06
min         2.901427e+04  0.000000e+00   0.000000e+00        2.901427e+04
25%         1.836373e+05  7.500000e+02   0.000000e+00        1.836373e+05
50%         5.451293e+05  1.600000e+04   0.000000e+00        5.451293e+05
75%         1.250014e+06  2.000000e+05   0.000000e+00        1.250014e+06
max         1.268378e+07  7.845000e+06   1.204500e+07        1.268378e+07

        KODE_TRAN  KODE_TRAN_TELLER
count  281.000000        219.000000
mean   115.366548       7112.452055
std    215.267668       2301.761131
min      1.000000       2501.000000
25%      2.000000       6669.000000
50%      2.000000       8506.000000
75%      4.000000       8508.000000
max    582.000000       9973.000000

In [9]:
def preprocess_data(data):
  # Menambahkan kolom baru
  data['amount'] = data['MUTASI_DEBET'] + data['MUTASI_KREDIT']

  # Menghapus kolom tidak terpakai
  data.drop(["ID","NOREK","TGL_EFEKTIF","JAM_TRAN","SEQ","DESK_TRAN","SALDO_AWAL_MUTASI",
             "MUTASI_DEBET", "MUTASI_KREDIT", "SALDO_AKHIR_MUTASI","TRUSER","KODE_TRAN",
             "KODE_TRAN_TELLER","TRREMK", "TLBDS1","TLBDS2","REMARK_CUSTOM"],
            axis = 1, inplace= True)

  # Mengganti nama kolom
  data.rename(columns={'TGL_TRAN':'date','GLSIGN':'transaction_type'}, inplace=True)

  # Mengganti isi kolom
  data['transaction_type'] = data['transaction_type'].replace({'Cr': 'Income', 'Db': 'Expense'})

  # Mengkonversi tipe data
  data['date'] = pd.to_datetime(data['date']).dt.date
  data['amount'] = pd.to_numeric(data['amount'])
  data['transaction_type'] = data['transaction_type'].astype('category')

  # Menghapus baris dengan missing value
  data.dropna(inplace=True)

  # Mengurutkan data
  data.sort_values(by='date', ascending=True)

  return data

In [10]:
preprocess_data(adit_df)

          date transaction_type     amount
0   2024-01-29           Income  2735000.0
1   2024-01-30           Income   300000.0
2   2024-01-30          Expense  2800000.0
3   2024-01-30          Expense     2500.0
4   2024-01-31          Expense   240000.0
..         ...              ...        ...
73  2024-11-18           Income   700000.0
74  2024-11-18          Expense   437000.0
75  2024-11-18          Expense     2500.0
76  2024-11-18          Expense   150000.0
77  2024-11-18          Expense     2500.0

[72 rows x 3 columns]

In [11]:
preprocess_data(alus_df)

           date transaction_type    amount
0    2024-01-02          Expense  680000.0
1    2024-01-02          Expense    2500.0
2    2024-01-02          Expense  100000.0
3    2024-01-02          Expense    1500.0
4    2024-01-02          Expense   15000.0
..          ...              ...       ...
248  2024-11-13           Income   50000.0
249  2024-11-14          Expense   30000.0
250  2024-11-15          Expense   20000.0
251  2024-11-15           Income  300000.0
252  2024-11-15          Expense   90000.0

[253 rows x 3 columns]

In [12]:
preprocess_data(amin_df)

           date transaction_type     amount
0    2023-09-01           Income  1200000.0
1    2023-09-04          Expense   200000.0
2    2023-09-04           Income   100000.0
3    2023-09-04          Expense   100000.0
4    2023-09-04          Expense   100000.0
..          ...              ...        ...
276  2024-11-05           Income   500000.0
277  2024-11-05          Expense   700000.0
278  2024-11-10          Expense     3000.0
279  2024-11-16          Expense     2500.0
280  2024-11-16          Expense     5500.0

[281 rows x 3 columns]

In [13]:
import json

data = pd.concat([adit_df, alus_df, amin_df]).sort_values(by='date', ascending=True)
data['date'] = data['date'].astype(str)

with open('merger_dataset.json', 'w') as json_file:
    json.dump(data.to_dict(orient="records"), json_file, indent=1)